# Generated by Django 4.2.3 on 2023-08-15 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="BIO",
            new_name="bio",
        ),
    ]
