# Generated by Django 4.2.3 on 2023-07-23 01:13

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='rooms/'),
        ),
    ]
