# Generated by Django 4.2.3 on 2023-07-25 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
    ]
