# Generated by Django 3.2 on 2023-07-23 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('size', models.IntegerField()),
                ('features', models.CharField(max_length=30)),
                ('description', djrichtextfield.models.RichTextField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='imgroomsbooking/')),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Booked')], default=0)),
                ('available_on', models.DateTimeField()),
                ('rating', models.ManyToManyField(blank=True, related_name='room_rate', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-size'],
            },
        ),
    ]
