# Generated by Django 4.2.3 on 2023-07-30 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", djrichtextfield.models.RichTextField(max_length=10000)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[400, 300],
                        upload_to="imgroomsbooking/",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Single-bedroom", "SINGLE-BEDROOM"),
                            ("Double-bedroom", "DOUBLE-BEDROOM"),
                            ("King-room", "KING-ROOM"),
                            ("Deluxe-room", "DELUXE-ROOM"),
                            ("Twin-room", "TWIN-ROOM"),
                        ],
                        default="Single-bedroom",
                        max_length=200,
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("number", models.IntegerField(default=1)),
                (
                    "features",
                    models.CharField(
                        choices=[
                            ("Balcony/terrace", "Balcony/terrace"),
                            ("Street view", "Street view"),
                            ("Garden view", "Garden view"),
                            ("Pool view", "Pool view"),
                        ],
                        default="Balcony/terrace",
                        max_length=30,
                    ),
                ),
                ("beds", models.IntegerField(default=1)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Room size: 30 m²/323 ft²", "Room size: 30 m²/323 ft²"),
                            ("Room size: 30 m²/323 ft²", "Room size: 35 m²/323 ft²"),
                            ("Room size: 30 m²/323 ft²", "Room size: 40 m²/323 ft²"),
                            ("Room size: 30 m²/323 ft²", "Room size: 45 m²/323 ft²"),
                        ],
                        default="Room size: 30 m²/323 ft²",
                        max_length=60,
                    ),
                ),
                (
                    "serviceOne",
                    models.CharField(
                        choices=[
                            ("Laundry and Dry-cleaner", "LAUNDRY AND DRY-CLEANER"),
                            (
                                "Bath, Sauna and Swimming-pool",
                                "BATH, SAUNA AND SWIMMING-POOL",
                            ),
                            (
                                "Billiard, Gym and Playground",
                                "BILLIARD, GYM AND PLAYGROUND",
                            ),
                            (
                                "Sport-Equipment and House-appliance",
                                "SPORT-EQUIMENT AND HOUSE-APPLIANCE",
                            ),
                            (
                                "Car-rent, restaurant and Tour-guide",
                                "CAR-RENT, RESTAURANT AND TOUR-GUIDE",
                            ),
                        ],
                        default="Laundry and Dry-cleaner",
                        max_length=200,
                    ),
                ),
                (
                    "serviceTwo",
                    models.CharField(
                        choices=[
                            ("Laundry and Dry-cleaner", "LAUNDRY AND DRY-CLEANER"),
                            (
                                "Bath, Sauna and Swimming-pool",
                                "BATH, SAUNA AND SWIMMING-POOL",
                            ),
                            (
                                "Billiard, Gym and Playground",
                                "BILLIARD, GYM AND PLAYGROUND",
                            ),
                            (
                                "Sport-Equipment and House-appliance",
                                "SPORT-EQUIMENT AND HOUSE-APPLIANCE",
                            ),
                            (
                                "Car-rent, restaurant and Tour-guide",
                                "CAR-RENT, RESTAURANT AND TOUR-GUIDE",
                            ),
                        ],
                        default="Laundry and Dry-cleaner",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[400, None],
                        upload_to="imgroomsbooking/",
                    ),
                ),
                (
                    "imageOne",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        null=True,
                        quality=75,
                        scale=None,
                        size=[400, None],
                        upload_to="imgroomsbooking/",
                    ),
                ),
                (
                    "imageTwo",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        null=True,
                        quality=75,
                        scale=None,
                        size=[400, None],
                        upload_to="imgroomsbooking/",
                    ),
                ),
                (
                    "rating",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_rate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="roombooking.room",
                    ),
                ),
            ],
            options={
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_out", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roombooking.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in"],
            },
        ),
    ]
