# Generated by Django 4.2.3 on 2023-07-28 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-number"]},
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                choices=[
                    ("Single-bedroom", "SINGLE-BEDROOM"),
                    ("Double-bedroom", "DOUBLE-BEDROOM"),
                    ("King-room", "KING-ROOM"),
                    ("Deluxe-room", "DELUXE-ROOM"),
                    ("Twin-room", "TWIN-ROOM"),
                ],
                default="Single-bedroom",
                on_delete=django.db.models.deletion.CASCADE,
                to="roombooking.room",
            ),
        ),
    ]
