# Generated by Django 4.2.3 on 2023-08-12 22:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="imageOne",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="imgroomsbooking/",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="imageTwo",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="imgroomsbooking/",
            ),
        ),
    ]
