# Generated by Django 4.2.3 on 2023-08-15 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roombooking", "0002_alter_room_imageone_alter_room_imagetwo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
