# Generated by Django 4.2.3 on 2023-07-28 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0002_alter_room_options_alter_booking_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="roombooking.room"
            ),
        ),
    ]
