# Generated by Django 4.2.3 on 2023-08-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0003_alter_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
