# Generated by Django 4.2.3 on 2023-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0003_alter_booking_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="serviceOne",
            field=models.CharField(
                choices=[
                    ("Laundry and Dry-cleaner", "LAUNDRY AND DRY-CLEANER"),
                    ("Bath, Sauna and Swimming-pool", "BATH, SAUNA AND SWIMMING-POOL"),
                    ("Billiard, Gym and Playground", "BILLIARD, GYM AND PLAYGROUND"),
                    (
                        "Sport-Equipment and House-appliance",
                        "SPORT-EQUIMENT AND HOUSE-APPLIANCE",
                    ),
                    (
                        "Car-rent, restaurant and Tour-guide",
                        "CAR-RENT, RESTAURANT AND TOUR-GUIDE",
                    ),
                ],
                default="Laundry and Dry-cleaner",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="serviceTwo",
            field=models.CharField(
                choices=[
                    ("Laundry and Dry-cleaner", "LAUNDRY AND DRY-CLEANER"),
                    ("Bath, Sauna and Swimming-pool", "BATH, SAUNA AND SWIMMING-POOL"),
                    ("Billiard, Gym and Playground", "BILLIARD, GYM AND PLAYGROUND"),
                    (
                        "Sport-Equipment and House-appliance",
                        "SPORT-EQUIMENT AND HOUSE-APPLIANCE",
                    ),
                    (
                        "Car-rent, restaurant and Tour-guide",
                        "CAR-RENT, RESTAURANT AND TOUR-GUIDE",
                    ),
                ],
                default="Laundry and Dry-cleaner",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="size",
            field=models.CharField(
                choices=[
                    ("Room size: 30 m²/323 ft²", "Room size: 30 m²/323 ft²"),
                    ("Room size: 30 m²/323 ft²", "Room size: 35 m²/323 ft²"),
                    ("Room size: 30 m²/323 ft²", "Room size: 40 m²/323 ft²"),
                    ("Room size: 30 m²/323 ft²", "Room size: 45 m²/323 ft²"),
                ],
                default="Room size: 30 m²/323 ft²",
                max_length=60,
            ),
        ),
    ]
