# Generated by Django 4.2.3 on 2023-07-25 17:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0004_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, 300],
                upload_to="imgroomsbooking/",
            ),
        ),
    ]
