# Generated by Django 4.2.3 on 2023-07-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0005_alter_about_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.IntegerField(choices=[(1, "Available"), (0, "Booked")]),
        ),
    ]
