# Generated by Django 4.2.3 on 2023-08-20 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "roombooking",
            "0006_alter_review_options_review_title_review_updated_on_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="average_rating",
        ),
    ]
