# Generated by Django 4.2.3 on 2023-07-27 12:20

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0006_alter_room_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=djrichtextfield.models.RichTextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="room",
            name="features",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
