# Generated by Django 4.2.3 on 2023-07-27 12:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0007_alter_room_description_alter_room_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="imgroomsbooking/",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.IntegerField(choices=[(1, "Available"), (0, "Not available")]),
        ),
    ]
