# Generated by Django 4.2.3 on 2023-07-27 12:57

from django.db import migrations, models
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0008_alter_room_image_alter_room_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=djrichtextfield.models.RichTextField(
                blank=True, max_length=10000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="features",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="imgroomsbooking/",
            ),
        ),
    ]
