# Generated by Django 4.2.3 on 2023-08-20 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0008_room_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="created_date",
            new_name="created_on",
        ),
    ]
