# Generated by Django 4.2.3 on 2023-07-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roombooking", "0009_alter_room_description_alter_room_features_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-number"]},
        ),
        migrations.RemoveField(
            model_name="room",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="room",
            name="price",
        ),
        migrations.RemoveField(
            model_name="room",
            name="size",
        ),
        migrations.RemoveField(
            model_name="room",
            name="user",
        ),
        migrations.AddField(
            model_name="room",
            name="beds",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="room",
            name="number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=djrichtextfield.models.RichTextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="room",
            name="features",
            field=models.CharField(
                choices=[
                    ("BA", "Balcony/terrace"),
                    ("ST", "Street view"),
                    ("GV", "Garden view"),
                    ("PV", "Pool view"),
                ],
                default="BA",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.IntegerField(choices=[(1, "Available"), (0, "Not availab")]),
        ),
        migrations.AlterField(
            model_name="room",
            name="title",
            field=models.CharField(
                choices=[
                    ("SNL", "SINGLE-BEDROOM"),
                    ("DBL", "DOUBLE-BEDROOM"),
                    ("KNG", "KING-ROOM"),
                    ("DLX", "DELUXE-ROOM"),
                    ("TWN", "TWIN-ROOM"),
                ],
                default="SNL",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roombooking.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in"],
            },
        ),
    ]
