# Generated by Django 4.2.3 on 2023-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0009_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
