# Generated by Django 4.2.3 on 2023-07-27 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0010_alter_room_options_remove_room_excerpt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
    ]
