# Generated by Django 4.2.3 on 2023-08-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0010_alter_review_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_on"]},
        ),
        migrations.RenameField(
            model_name="review",
            old_name="created_at",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="updated_at",
            new_name="updated_on",
        ),
        migrations.AlterField(
            model_name="review",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="roombooking.room",
            ),
        ),
    ]
