# Generated by Django 4.2.3 on 2023-07-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0011_remove_room_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="features",
            field=models.CharField(
                choices=[
                    ("Balcony/terrace", "Balcony/terrace"),
                    ("Street view", "Street view"),
                    ("Garden view", "Garden view"),
                    ("Pool view", "Pool view"),
                ],
                default="BA",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="title",
            field=models.CharField(
                choices=[
                    ("Single-bedroom", "SINGLE-BEDROOM"),
                    ("Double-bedroom", "DOUBLE-BEDROOM"),
                    ("King-room", "KING-ROOM"),
                    ("Deluxe-room", "DELUXE-ROOM"),
                    ("Twin-room", "TWIN-ROOM"),
                ],
                default="SNL",
                max_length=200,
            ),
        ),
    ]
