# Generated by Django 4.2.3 on 2023-08-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0011_alter_review_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
