# Generated by Django 4.2.3 on 2023-08-17 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0012_alter_review_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="review",
            new_name="comment",
        ),
        migrations.RemoveField(
            model_name="review",
            name="status",
        ),
    ]
