# Generated by Django 4.2.3 on 2023-08-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0013_rename_review_review_comment_remove_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
