# Generated by Django 4.2.3 on 2023-07-27 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0013_remove_room_available_on_alter_room_features_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
