# Generated by Django 4.2.3 on 2023-08-23 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0013_alter_room_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_on",
            field=models.DateField(auto_now=True),
        ),
    ]
