# Generated by Django 4.2.3 on 2023-08-24 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roombooking", "0014_alter_booking_check_in_alter_booking_check_out_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-ch_in"]},
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="check_in",
            new_name="ch_in",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="check_out",
            new_name="ch_out",
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="re",
                to="roombooking.room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="features",
            field=models.CharField(
                choices=[
                    ("Balcony/terrace", "Balcony/terrace"),
                    ("Street view", "Street view"),
                    ("Garden view", "Garden view"),
                    ("Pool view", "Pool view"),
                ],
                default="Balcony/terrace",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="serviceOne",
            field=models.CharField(
                choices=[
                    ("Laundry", "LAUNDRY"),
                    ("Bath, Sauna and Swimming-pool", "BATH, SAUNA AND SWIMMING-POOL"),
                    ("Billiard, Gym and Playground", "BILLIARD, GYM AND PLAYGROUND"),
                    ("House-appliance", "HOUSE-APPLIANCE"),
                    ("Car-rent, and Tour-guide", "CAR-RENT, AND TOUR-GUIDE"),
                ],
                default="Laundry",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="serviceTwo",
            field=models.CharField(
                choices=[
                    ("Laundry", "LAUNDRY"),
                    ("Bath, Sauna and Swimming-pool", "BATH, SAUNA AND SWIMMING-POOL"),
                    ("Billiard, Gym and Playground", "BILLIARD, GYM AND PLAYGROUND"),
                    ("House-appliance", "HOUSE-APPLIANCE"),
                    ("Car-rent, and Tour-guide", "CAR-RENT, AND TOUR-GUIDE"),
                ],
                default="Laundry",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="title",
            field=models.CharField(
                choices=[
                    ("Single-bedroom", "SINGLE-BEDROOM"),
                    ("Double-bedroom", "DOUBLE-BEDROOM"),
                    ("King-room", "KING-ROOM"),
                    ("Deluxe-room", "DELUXE-ROOM"),
                    ("Twin-room", "TWIN-ROOM"),
                ],
                default="Single-bedroom",
            ),
        ),
    ]
