# Generated by Django 4.2.3 on 2023-08-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0016_alter_review_rating_alter_review_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                default=5,
            ),
        ),
    ]
