# Generated by Django 4.2.3 on 2023-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roombooking", "0017_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
